services:
  servers:
    image: leave_platform_container
    container_name: leave_platform_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8081:80"
    networks:
      - hub-network
      
  sqlserver:
    container_name: sqlserver
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345#
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - hub-network
    volumes:
      - sql-data:/var/opt/sqlserver

networks:
  hub-network:
    driver: bridge
    
volumes:
  sql-data: