name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Adjust this if your Dockerfile is in a different location
          target: build
          load: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/LeaveForms:build

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Adjust this if your Dockerfile is in a different location
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/LeaveForms:latest
